openapi: 3.0.0

info:
  title: API - Mapa Istmo
  version: 1.0.0
  description: API segura con login y JWT para consultar capas geográficas del Istmo de Tehuantepec.

servers:
  - url: https://api-mapa-istmo.onrender.com

paths:
  /api/auth/login:
    post:
      summary: Iniciar sesión
      description: Retorna un token JWT si las credenciales son válidas.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Token generado correctamente
        '401':
          description: Credenciales inválidas

  /api/capas/{nombre}:
    get:
      summary: Obtener capa geoespacial
      description: Devuelve un GeoJSON con los datos de la capa solicitada.
      parameters:
        - in: path
          name: nombre
          required: true
          schema:
            type: string
          description: Nombre de la capa (ej. aeropuertos, puertos, rutas_ffcc, etc.)
        - in: query
          name: page
          schema:
            type: integer
          description: Página de resultados (paginación opcional)
        - in: query
          name: limit
          schema:
            type: integer
          description: Número máximo de elementos por página
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Datos de la capa en formato GeoJSON
        '401':
          description: No autorizado

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
