openapi: 3.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []

info:
  title: API - Mapa Istmo
  version: 1.0.0
  description: API segura con login y JWT para consultar capas geográficas.

servers:
  - url: https://api-mapa-istmo.onrender.com

paths:
  /api/auth/login:
    post:
      summary: Iniciar sesión
      description: Retorna un token JWT si las credenciales son válidas.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Token generado correctamente

  /api/capas/{nombre}:
    get:
      summary: Obtener capa geoespacial
      description: Devuelve un GeoJSON con los datos de la capa solicitada.
      parameters:
        - in: path
          name: nombre
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Datos de la capa
        '401':
          description: No autorizado

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
