openapi: 3.0.0
info:
  title: API - Mapa Istmo
  version: 1.0.0
  description: |
    API pública que expone capas geoespaciales del Istmo de Tehuantepec desde una base de datos PostgreSQL/PostGIS.  
    Las capas disponibles incluyen puntos, líneas y polígonos como aeropuertos, puertos, rutas y coberturas de red.  
    Los resultados se devuelven en formato GeoJSON.

servers:
  - url: https://api-mapa-istmo.onrender.com

paths:
  /api/capas/{nombre}:
    get:
      summary: Obtener datos de una capa geoespacial
      description: |
        Devuelve los datos de la capa indicada por el nombre en formato GeoJSON.  
        Soporta paginación con los parámetros `page` y `limit`.

        Ejemplo:  
        `/api/capas/red_att_4g?page=1&limit=1000`
      parameters:
        - name: nombre
          in: path
          required: true
          description: Nombre de la capa a consultar (por ejemplo: `aeropuertos`, `rutas_ffcc`, `zonaciit`)
          schema:
            type: string
        - name: page
          in: query
          required: false
          description: Página de resultados (por defecto 1)
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          required: false
          description: Cantidad de registros por página (por defecto 1000)
          schema:
            type: integer
            default: 1000
      responses:
        '200':
          description: GeoJSON con los datos de la capa
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: FeatureCollection
                  features:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          example: Feature
                        geometry:
                          type: object
                        properties:
                          type: object
                          properties:
                            id:
                              type: integer
                            nombre:
                              type: string
                            tipo:
                              type: string
                            categoria:
                              type: string
        '500':
          description: Error al consultar la capa
